version: '3.8'

services:
  bullboard:
    container_name: bullboard-dev
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USE_TLS: false
      REDIS_PASSWORD: ''
      BULL_PREFIX: bull
      BULL_VERSION: BULLMQ
      USER_LOGIN: ''
      USER_PASSWORD: ''
      REDIS_DB: 0
      PROXY_PATH: ''

networks:
  default:
    name: dev-master
    external: true
