version: 2.1
orbs:
  docker: circleci/docker@2.0.1
jobs:
  release:
    docker:
      - image: 'circleci/node:lts'
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: release
          command: yarn release || true
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - docker/check
      - docker/build:
          image: thalesog/bullboard
      - docker/push:
          digest-path: /tmp/digest.txt
          image: thalesog/bullboard
          tag: $CIRCLE_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  version: 2
  release:
    jobs:
      - release
  build-master:
    jobs:
      - build-and-push:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
