version: 2.1
orbs:
  docker: circleci/docker@2.0.1
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: thalesog/bullboard
      - docker/push:
          digest-path: /tmp/digest.txt
          image: thalesog/bullboard
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  version: 2
  build-master:
    jobs:
      - build-and-push:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
